name: uta_reader_app
description: Japanese Text Analyzer App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  mecab_for_flutter: ^1.0.6
  ruby_text: ^3.0.3
  jm_dict: ^0.2.0
  translator: ^1.0.4+1
  http: ^1.1.0
  window_manager: ^0.4.0
  path_provider: ^2.1.1
  path: ^1.8.3
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/ipadic/

  fonts:
  - family: NotoSansJP
    fonts:
      - asset: assets/fonts/NotoSansJP-Regular.ttf
      - asset: assets/fonts/NotoSansJP-Bold.ttf
        weight: 700
